.PHONY: test security run stop compose-up compose-down

BUILD_DIR = $(PWD)/app

security:
	gosec -quiet ./...

test: security
	go test -v -timeout 30s -coverprofile=cover.out -cover ./...
	go tool cover -func=cover.out

BASE_SERVER_NAME="Portfolio API Service"
BASE_SERVER_URL="0.0.0.0:3100"
BASE_SERVER_READ_TIMEOUT="60"
BASE_DB_SERVER_URL="host=localhost port=5432 user=user password=password dbname= sslmode=disable"

go:
	export BASE_SERVER_NAME=$(BASE_SERVER_NAME); \
	export BASE_SERVER_URL=$(BASE_SERVER_URL); \
	export BASE_SERVER_READ_TIMEOUT=$(BASE_SERVER_READ_TIMEOUT); \
	export BASE_DB_SERVER_URL=$(BASE_DB_SERVER_URL); \
	go mod tidy;\
	go run main.go

docker_build_image:
	docker build -t portfolio_api:latest .

docker_app: docker_build_image
	docker run -d \
	            --restart unless-stopped \
        		--name portfolio_api_container \
        		--network host \
        		-e BASE_SERVER_NAME=$(BASE_SERVER_NAME) \
        		-e BASE_SERVER_URL=$(BASE_SERVER_URL) \
        		-e BASE_SERVER_READ_TIMEOUT=$(BASE_SERVER_READ_TIMEOUT) \
        		-e BASE_DB_SERVER_URL=$(BASE_DB_SERVER_URL) \
        		portfolio_api:latest

run: docker_app
stop:
	docker container stop portfolio_api_container
	docker container rm portfolio_api_container
	docker rmi dinkes_sdk:latest

compose-up:
	docker-compose up -d
compose-down:
	docker-compose down
