// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/about": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Showing list of all portofolio data.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "About"
                ],
                "summary": "Endpoint for Portoflio Pages (http://yoviealfaguistuta.site)",
                "operationId": "about",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.About"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/configs.RequestError"
                        }
                    },
                    "404": {
                        "description": "Data not found",
                        "schema": {
                            "$ref": "#/definitions/configs.RequestError"
                        }
                    },
                    "422": {
                        "description": "Data validation failed",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/configs.DataValidationError"
                            }
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/configs.ServerError"
                        }
                    }
                }
            }
        },
        "/portofolio/detail/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Showing list of all portofolio data.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Portofolio"
                ],
                "summary": "Endpoint for Portoflio Pages (http://yoviealfaguistuta.site)",
                "operationId": "portofolio-detail",
                "parameters": [
                    {
                        "type": "number",
                        "description": "Id Portofolio",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.PortofolioDetail"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/configs.RequestError"
                        }
                    },
                    "404": {
                        "description": "Data not found",
                        "schema": {
                            "$ref": "#/definitions/configs.RequestError"
                        }
                    },
                    "422": {
                        "description": "Data validation failed",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/configs.DataValidationError"
                            }
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/configs.ServerError"
                        }
                    }
                }
            }
        },
        "/portofolio/index": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Showing list of all portofolio data.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Portofolio"
                ],
                "summary": "Endpoint for Portoflio Pages (http://yoviealfaguistuta.site)",
                "operationId": "portofolio-list",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.PortofolioList"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/configs.RequestError"
                        }
                    },
                    "404": {
                        "description": "Data not found",
                        "schema": {
                            "$ref": "#/definitions/configs.RequestError"
                        }
                    },
                    "422": {
                        "description": "Data validation failed",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/configs.DataValidationError"
                            }
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/configs.ServerError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "configs.DataValidationError": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "configs.RequestError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "configs.ServerError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.About": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "I am .. years old"
                }
            }
        },
        "models.PortofolioDetail": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "object"
                },
                "databases": {
                    "type": "string",
                    "example": "PostgreSql"
                },
                "dates": {
                    "type": "string",
                    "example": "1 Januari 2022"
                },
                "descriptions": {
                    "type": "string",
                    "example": "Indeks Pengelolaan Keuangan Daerah"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PortofolioImagesModel"
                    }
                },
                "languages": {
                    "type": "string",
                    "example": "Javascript"
                },
                "platform": {
                    "type": "string",
                    "example": "Website"
                },
                "project_info": {
                    "type": "string",
                    "example": "Sistem ini dibangun pada tahun 2021"
                },
                "source_code": {
                    "type": "string",
                    "example": "https://github.com/*project"
                },
                "title": {
                    "type": "string",
                    "example": "IPKD"
                },
                "updated_at": {
                    "type": "object"
                },
                "urls": {
                    "type": "string",
                    "example": "https://ipkd-bpp.kemendagri.go.id"
                }
            }
        },
        "models.PortofolioImagesModel": {
            "type": "object",
            "properties": {
                "images": {
                    "type": "string",
                    "example": "/assets/png"
                },
                "orders": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.PortofolioList": {
            "type": "object",
            "properties": {
                "descriptions": {
                    "type": "string",
                    "example": "Indeks Pengelolaan Keuangan Daerah"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "images": {
                    "type": "string",
                    "example": "/assets/*png"
                },
                "title": {
                    "type": "string",
                    "example": "IPKD"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
